In [2]:
! pip install torch

In [3]:
! pip3 install torch torchvision torchaudio

In [36]:
inputs.shape
attention_score  =torch.empty(inputs.shape[0])
for i,x in enumerate(inputs):
    attention_score[i] = torch.dot(x,inputs[1])
# attention_score

In [35]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

inputs[1]

tensor([0.5500, 0.8700, 0.6600])

In [37]:
query = inputs[1]
print(query)

tensor([0.5500, 0.8700, 0.6600])


In [16]:
torch.dot(inputs[1] ,inputs[2])

tensor(1.4754)

In [38]:
attention_score = torch.ones(inputs.shape[0])
query = inputs[1]
for i,x_1  in enumerate(inputs):
    attention_score[i] = torch.dot(x_1,query)
    print(attention_score[i])

tensor(0.9544)
tensor(1.4950)
tensor(1.4754)
tensor(0.8434)
tensor(0.7070)
tensor(1.0865)


In [40]:
# attention_score
print(query.shape,x_1.shape)


torch.Size([3]) torch.Size([3])


In [12]:
attention_sc = torch.ones(inputs.shape[0])
attention_sc
for i,x in enumerate(inputs):
    for j,k in enumerate( inputs):
        print(inputs[i][j])

tensor(0.4300)
tensor(0.1500)
tensor(0.8900)


IndexError: index 3 is out of bounds for dimension 0 with size 3

In [41]:
for i in attention_score:
    print(i)

tensor(0.9544)
tensor(1.4950)
tensor(1.4754)
tensor(0.8434)
tensor(0.7070)
tensor(1.0865)


In [14]:
def softmax(x):
    
    return torch.exp(x)/torch.exp(x).sum(dim =0)
attention_sc_2 = softmax(attention_score)
print(sum(attention_sc_2))

tensor(1.0000)


In [42]:
attention_weights = torch.softmax(attention_score,dim =0)
print(attention_weights)


tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


In [43]:
print(attention_weights.sum())

tensor(1.)


In [45]:
query  = inputs[1]
context_vec= torch.zeros(query.shape)
print(inputs[1])
print(context_vec)
for i,x_1 in enumerate(inputs):
    context_vec += attention_weights[i]*x_1

print(context_vec)

tensor([0.5500, 0.8700, 0.6600])
tensor([0., 0., 0.])
tensor([0.4419, 0.6515, 0.5683])


In [31]:
attention_weights.shape , x_1

(torch.Size([6, 6]), tensor([0.0500, 0.8000, 0.5500]))

In [24]:
print(inputs)

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])


###  Computing attention weights for all input tokens

In [46]:
attn_scores = torch.empty(6, 6)

for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)

print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [48]:
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        print(x_i,x_j)

tensor([0.4300, 0.1500, 0.8900]) tensor([0.4300, 0.1500, 0.8900])
tensor([0.4300, 0.1500, 0.8900]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.4300, 0.1500, 0.8900]) tensor([0.5700, 0.8500, 0.6400])
tensor([0.4300, 0.1500, 0.8900]) tensor([0.2200, 0.5800, 0.3300])
tensor([0.4300, 0.1500, 0.8900]) tensor([0.7700, 0.2500, 0.1000])
tensor([0.4300, 0.1500, 0.8900]) tensor([0.0500, 0.8000, 0.5500])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.4300, 0.1500, 0.8900])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.5700, 0.8500, 0.6400])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.2200, 0.5800, 0.3300])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.7700, 0.2500, 0.1000])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.0500, 0.8000, 0.5500])
tensor([0.5700, 0.8500, 0.6400]) tensor([0.4300, 0.1500, 0.8900])
tensor([0.5700, 0.8500, 0.6400]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.5700, 0.8500, 0.6400]) tensor([0.5700, 0.8500, 0.6400])
tensor([0.

In [20]:
inputs.shape

torch.Size([6, 3])

In [50]:
attention_weights = torch.softmax(attn_scores,dim = -1,)
attention_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [63]:
attn_1 =inputs @ inputs.T
attn_2 = torch.matmul(inputs , inputs.T)
# attn_3 = torch.dot(inputs,inputs.T)

attn_1== attn_2

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1

In [61]:
import torch.nn as nn
m = nn.Softmax(dim=-1)
input = torch.randn(2, 3)
output = m(input)
print(output)

tensor([[0.4646, 0.3685, 0.1669],
        [0.5558, 0.2716, 0.1726]])


In [60]:
attn_weights= torch.softmax(attn_1,dim =-1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [66]:
context_vec = attn_weights @ inputs 
print(context_vec.shape
     )
print(context_vec[0])

torch.Size([6, 3])
tensor([0.4421, 0.5931, 0.5790])


## Computing the attention weights 

In [94]:
x_2 = inputs[1] # second input element
d_in = inputs.shape[1] # the input embedding size, d=3
d_out = 2 

In [95]:
x_2,d_in,d_out

(tensor([0.5500, 0.8700, 0.6600]), 3, 2)

In [69]:
torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key.shape,W_query

(torch.Size([3, 2]),
 Parameter containing:
 tensor([[0.2961, 0.5166],
         [0.2517, 0.6886],
         [0.0740, 0.8665]]))

In [70]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2,key_2.shape)

tensor([0.4306, 1.4551]) torch.Size([2])


In [74]:
 torch.matmul(x_2,W_query)

tensor([0.4306, 1.4551])

In [75]:
keys = inputs @ W_key 
values = inputs @ W_value

print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


In [78]:
keys[2],values

(tensor([0.4361, 1.1156]),
 tensor([[0.1855, 0.8812],
         [0.3951, 1.0037],
         [0.3879, 0.9831],
         [0.2393, 0.5493],
         [0.1492, 0.3346],
         [0.3221, 0.7863]]))

In [80]:
keys_2 = keys[2]
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.8111)


In [87]:
attn_Score_2 = query_2 @ keys.T
d_k = keys.shape[1]
import math
attn_weights_2 = torch.softmax(attn_Score_2 /math.sqrt(d_k),dim =-1 )
attn_weights_2

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])

In [88]:
context_vec_2 = attn_weights_2 @ values

In [89]:
context_vec_2

tensor([0.3061, 0.8210])

##  Implementing a compact SelfAttention class

In [96]:
import torch.nn as nn
class selfAttention_v1(nn.Module):
    
    def __init__(self,d_in,d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))
        
    def forward(self,x):
        keys =  x @ self.W_key
        queries= x @ self.W_query
        values = x@ self.W_value
        attn_score =  queries @ keys.T
        attn_weights = torch.softmax(
        attn_score / math.sqrt(keys.shape[-1]),dim =-1)
        context_vec = attn_weights @ values
        return context_vec

torch.manual_seed(1233)
sa_v1 = selfAttention_v1(d_in,d_out)
print(sa_v1(inputs))

        
        

tensor([[1.0949, 0.9075],
        [1.1209, 0.9305],
        [1.1194, 0.9293],
        [1.0644, 0.8803],
        [1.0572, 0.8736],
        [1.0846, 0.8986]], grad_fn=<MmBackward0>)


In [103]:
torch.rand(d_in,d_out)
d_in,d_out

(3, 2)

In [116]:
import torch
import torch.nn as nn

class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values
        return context_vec

# Now, let's create an instance of the class
torch.manual_seed(1233)
d_in, d_out = 3,2 #Define input and output dimensions
sa_v2 = SelfAttention_v2(d_in, d_out)

# # Define an example input
# inputs = torch.tensor([[0.4, 0.5, 0.6, 0.7], 
#                        [0.1, 0.2, 0.3, 0.4], 
#                        [0.9, 1.0, 1.1, 1.2]])

# Pass the input through the self-attention layer
output = sa_v2(inputs)
print(output)
print(attn_v2)


tensor([[-0.1363,  0.4183],
        [-0.1384,  0.4209],
        [-0.1379,  0.4203],
        [-0.1367,  0.4181],
        [-0.1270,  0.4056],
        [-0.1415,  0.4245]], grad_fn=<MmBackward0>)
tensor([[0.1669, 0.1774, 0.1768, 0.1585, 0.1550, 0.1654],
        [0.1675, 0.1802, 0.1793, 0.1566, 0.1500, 0.1664],
        [0.1674, 0.1794, 0.1786, 0.1572, 0.1512, 0.1663],
        [0.1676, 0.1756, 0.1750, 0.1601, 0.1544, 0.1673],
        [0.1648, 0.1618, 0.1623, 0.1695, 0.1783, 0.1632],
        [0.1685, 0.1836, 0.1823, 0.1544, 0.1426, 0.1686]],
       grad_fn=<SoftmaxBackward0>)


## Applying a causal attention mask

In [119]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_score = queries @ keys.T
values = sa_v2.W_value(inputs)
attn_weights = torch.softmax(attn_score/ math.sqrt(keys.shape[-1]),dim =-1)
                   
print(attn_weights)
# context_vec = attn_weights  @ values


tensor([[0.1669, 0.1774, 0.1768, 0.1585, 0.1550, 0.1654],
        [0.1675, 0.1802, 0.1793, 0.1566, 0.1500, 0.1664],
        [0.1674, 0.1794, 0.1786, 0.1572, 0.1512, 0.1663],
        [0.1676, 0.1756, 0.1750, 0.1601, 0.1544, 0.1673],
        [0.1648, 0.1618, 0.1623, 0.1695, 0.1783, 0.1632],
        [0.1685, 0.1836, 0.1823, 0.1544, 0.1426, 0.1686]],
       grad_fn=<SoftmaxBackward0>)


In [125]:
context_length = attn_scores.shape[0]
mask = torch.tril(torch.tensor([[[23,53],[24,53],[23,54]],
                               [[23,53],[43,45],[64,2345]]]))
print(mask)

tensor([[[  23,    0],
         [  24,   53],
         [  23,   54]],

        [[  23,    0],
         [  43,   45],
         [  64, 2345]]])


In [126]:
mask_sample = torch.tril(torch.ones(context_length,context_length))
print(mask_sample)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [129]:
row_sums = mask_sample.sum(dim =-1,keepdim =True)
masked_simple_norm = mask_sample/ row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]])


In [130]:
attn_weights

tensor([[0.1669, 0.1774, 0.1768, 0.1585, 0.1550, 0.1654],
        [0.1675, 0.1802, 0.1793, 0.1566, 0.1500, 0.1664],
        [0.1674, 0.1794, 0.1786, 0.1572, 0.1512, 0.1663],
        [0.1676, 0.1756, 0.1750, 0.1601, 0.1544, 0.1673],
        [0.1648, 0.1618, 0.1623, 0.1695, 0.1783, 0.1632],
        [0.1685, 0.1836, 0.1823, 0.1544, 0.1426, 0.1686]],
       grad_fn=<SoftmaxBackward0>)

In [134]:
# mask = torch.triu(torch.ones(context_length,context_length))
# masked = attn_score.masked_fill(mask.bool(),-torch.inf)
# print(masked)
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[0.9995,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.9544, 1.4950,   -inf,   -inf,   -inf,   -inf],
        [0.9422, 1.4754, 1.4570,   -inf,   -inf,   -inf],
        [0.4753, 0.8434, 0.8296, 0.4937,   -inf,   -inf],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654,   -inf],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [141]:
attn_weights = torch.softmax(masked/ math.sqrt(keys.shape[-1]),dim =-1)
print(attn_weights.sum(dim =-1))


tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


## Masking additional attention weights with dropout

In [147]:
dropout = torch.nn.Dropout(0.5)
print(dropout(attn_weights))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.1888, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.7482, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4352, 0.0000, 0.0000, 0.4409, 0.0000, 0.0000],
        [0.0000, 0.4357, 0.0000, 0.0000, 0.4230, 0.0000],
        [0.2946, 0.4065, 0.0000, 0.2999, 0.2320, 0.0000]])


## Implementing a compact causal self-attention class

In [155]:
batch = torch.stack((inputs,inputs),dim =0)
batch,batch.shape

(tensor([[[0.4300, 0.1500, 0.8900],
          [0.5500, 0.8700, 0.6600],
          [0.5700, 0.8500, 0.6400],
          [0.2200, 0.5800, 0.3300],
          [0.7700, 0.2500, 0.1000],
          [0.0500, 0.8000, 0.5500]],
 
         [[0.4300, 0.1500, 0.8900],
          [0.5500, 0.8700, 0.6600],
          [0.5700, 0.8500, 0.6400],
          [0.2200, 0.5800, 0.3300],
          [0.7700, 0.2500, 0.1000],
          [0.0500, 0.8000, 0.5500]]]),
 torch.Size([2, 6, 3]))

In [153]:
class CasualAttention(nn.Module):
    
    def __init__(self,d_in,d_out,context_length,dropout,qkv_bias = False):
        super().__init__()
        self.d_out =d_out
        self.W_query = nn.Linear(d_in,d_out,bias = qkv_bias)
        self.W_key = nn.Linear(d_in,d_out,bias = qkv_bias)
        self.W_value = nn.Linear(d_in,d_out,bias = qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New
        
    def forward(self,x):
        b,num_tokens ,d_in = x.shape
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)  # `:num_tokens` to account for cases where the number of tokens in the batch is smaller than the supported context_size
        attn_weights = torch.softmax(
            attn_scores / math.sqrt(keys.shape[-1]), dim=-1
        )
        attn_weights = self.dropout(attn_weights) # New

        context_vec = attn_weights @ values
        return context_vec

torch.manual_seed(123)

context_lenght = batch.shape[1]
ca = CasualAttention(d_in,d_out,context_lenght,0.0)
context_vecs =ca(batch)  # batch shape [2, 6, 3]
#   b,num_tokens ,d_in = x.shape [x = batch],,
#   2  6        3
print(context_vecs)
print(context_vecs.shape)

tensor([[[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]],

        [[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]]], grad_fn=<UnsafeViewBackward0>)
torch.Size([2, 6, 2])


In [161]:
batch[0],batch[[1]],batch

(tensor([[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]]),
 tensor([[[0.4300, 0.1500, 0.8900],
          [0.5500, 0.8700, 0.6600],
          [0.5700, 0.8500, 0.6400],
          [0.2200, 0.5800, 0.3300],
          [0.7700, 0.2500, 0.1000],
          [0.0500, 0.8000, 0.5500]]]),
 tensor([[[0.4300, 0.1500, 0.8900],
          [0.5500, 0.8700, 0.6600],
          [0.5700, 0.8500, 0.6400],
          [0.2200, 0.5800, 0.3300],
          [0.7700, 0.2500, 0.1000],
          [0.0500, 0.8000, 0.5500]],
 
         [[0.4300, 0.1500, 0.8900],
          [0.5500, 0.8700, 0.6600],
          [0.5700, 0.8500, 0.6400],
          [0.2200, 0.5800, 0.3300],
          [0.7700, 0.2500, 0.1000],
          [0.0500, 0.8000, 0.5500]]]))

## MultiHead Attention --FInally

In [166]:
class MultiHeadAttention(nn.Module):
    def __init__(self,d_in,d_out,context_length,dropout,num_heads,qkv_bias= False):
        super().__init__()
        self.head=nn.ModuleList(
        [CasualAttention(d_in, d_out, context_length, dropout, qkv_bias) 
             for _ in range(num_heads)])
    def forward(self,x):
        return torch.cat([head(x ) for head in self.head],dim =-1)
    
torch.manual_seed(123)

context_length = batch.shape[1] # This is the number of tokens
d_in, d_out = 3, 2
mha = MultiHeadAttention(
    d_in, d_out, context_length, 0.0, num_heads=2
)

context_vecs = mha(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]],

        [[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]]], grad_fn=<CatBackward0>)
context_vecs.shape: torch.Size([2, 6, 4])


In [170]:
multihead_attn = nn.MultiheadAttention(6,4)
attn_output, attn_output_weights = multihead_attn(query, key, value)

AssertionError: embed_dim must be divisible by num_heads