In [1]:

x = 10
print(x)



10


In [1]:
with open("text.txt",'r', encoding = "utf-8")  as f:
    text = f.read()

    # Count the number of occurrences of each word
    word_counts = {}
    for word in text.lower().split():
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1


In [2]:
word_counts

{'\ufeff': 1,
 'israel': 331,
 'potter': 6,
 'his': 925,
 'fifty': 10,
 'years': 25,
 'of': 2200,
 'exile': 8,
 'by': 393,
 'herman': 1,
 'melville': 1,
 'biography,': 1,
 'in': 1198,
 'its': 77,
 'purer': 1,
 'form,': 2,
 'confined': 4,
 'to': 1619,
 'the': 4717,
 'ended': 3,
 'lives': 3,
 'true': 16,
 'and': 1395,
 'brave,': 1,
 'may': 44,
 'be': 301,
 'held': 8,
 'fairest': 1,
 'meed': 1,
 'human': 15,
 'virtue—one': 1,
 'given': 10,
 'received': 19,
 'entire': 5,
 'disinterestedness—since': 1,
 'neither': 13,
 'can': 26,
 'biographer': 1,
 'hope': 8,
 'for': 436,
 'acknowledgment': 1,
 'from': 316,
 'subject,': 4,
 'nor': 27,
 'subject': 8,
 'at': 533,
 'all': 260,
 'avail': 1,
 'himself': 105,
 'biographical': 1,
 'distinction': 1,
 'conferred.': 1,
 'well': 41,
 'merits': 2,
 'present': 36,
 'tribute—a': 1,
 'private': 23,
 'bunker': 13,
 'hill,': 7,
 'who': 97,
 'faithful': 1,
 'services': 5,
 'was': 637,
 'ago': 3,
 'promoted': 2,
 'a': 1635,
 'still': 55,
 'deeper': 4,
 'priva

In [3]:
print(len(text))

379877


In [4]:
chars =  sorted(set(text))

print(len(chars))
string_to_int = { ch:i for i,ch in enumerate(chars)}
int_to_string = { i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: "".join([int_to_string[i] for i in l])

85


In [7]:
encode

<function __main__.<lambda>(s)>

In [8]:
encode('hello')

[58, 55, 62, 62, 65]

In [10]:
decode([58, 55, 62, 62, 65])

'hello'

In [11]:
import torch as tc

In [12]:
data = tc.tensor(encode(text),dtype = tc.long)

In [14]:
data[:100]

tensor([84,  0, 30, 40, 39, 22, 26, 33,  1, 37, 36, 41, 41, 26, 39,  0,  0, 29,
        59, 69,  1, 27, 59, 56, 70, 75,  1, 46, 55, 51, 68, 69,  1, 65, 56,  1,
        26, 74, 59, 62, 55,  0,  0, 23, 75,  1, 29, 55, 68, 63, 51, 64,  1, 34,
        55, 62, 72, 59, 62, 62, 55,  0,  0, 23, 59, 65, 57, 68, 51, 66, 58, 75,
         6,  1, 59, 64,  1, 59, 70, 69,  1, 66, 71, 68, 55, 68,  1, 56, 65, 68,
        63,  6,  1, 53, 65, 64, 56, 59, 64, 55])

In [15]:
n = int(0.7 * len(data))
train_data = data[:n]
val_data = data[n:]

In [18]:
block_size= 8
x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
    context =x[:i+1]
    target = y[i]
    print("context ,",context,"target " ,target)

context , tensor([84]) target  tensor(0)
context , tensor([84,  0]) target  tensor(30)
context , tensor([84,  0, 30]) target  tensor(40)
context , tensor([84,  0, 30, 40]) target  tensor(39)
context , tensor([84,  0, 30, 40, 39]) target  tensor(22)
context , tensor([84,  0, 30, 40, 39, 22]) target  tensor(26)
context , tensor([84,  0, 30, 40, 39, 22, 26]) target  tensor(33)
context , tensor([84,  0, 30, 40, 39, 22, 26, 33]) target  tensor(1)


In [21]:
import torch
device = "cuda"if torch.cuda.is_available() else "cpu"
device

'cpu'

In [23]:
torch.randint(-100,100,(6,3))

tensor([[  7,  37,  12],
        [-27, -93, -90],
        [-42, -16,  75],
        [-44,  73,  32],
        [-44,  -7,  87],
        [-42, -44,  97]])

In [26]:
torch.tensor([[0.1,1.2],[23,1.01]])

tensor([[ 0.1000,  1.2000],
        [23.0000,  1.0100]])

In [27]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
vacob_size = 1000
embedding_dim =100

embedding = torch.nn.Embedding(vacob_size,embedding_dim)
input_indices = torch.LongTensor([1,2,4,8])

output = embedding(input_indices)
print(input_indices)
print(output)

tensor([1, 2, 4, 8])
tensor([[ 0.4613,  0.6034,  0.4466, -0.7948, -0.4906, -0.1702, -0.1317, -0.4822,
          0.7040, -2.3161,  0.2673, -0.0809,  1.4267,  0.7330, -1.1810, -0.5984,
         -1.5275, -1.8489,  1.2644,  0.2927,  0.5797, -0.5363, -1.4628, -1.2297,
          1.3876,  0.4333, -0.3729,  1.1690,  0.7333,  1.0482,  1.9135, -0.8469,
         -1.5505,  0.1275,  1.5589, -1.8901,  0.6752,  0.7384, -0.0925,  0.6523,
         -0.3173, -0.6387,  1.7827,  0.0823, -0.1895,  1.3631, -1.6190, -0.4071,
          0.6634,  1.2761,  0.0538,  1.9837,  0.1054,  0.1177,  0.0331,  0.7173,
          0.6941, -0.4982,  1.9202, -0.1519, -0.4696, -0.7761,  0.0710, -0.0651,
          0.4306, -0.5332,  1.2273,  0.2401, -0.8424,  1.0454, -0.4165, -0.4589,
          1.4575,  0.1474, -0.3036,  0.6501,  0.1150,  1.4038,  0.0973, -0.3756,
          0.8577, -1.3734,  0.4185,  1.9215, -0.1580,  0.3267, -0.7813, -0.2179,
         -0.7528,  0.2492, -1.0802, -2.1354, -0.3020,  0.8017, -0.3273,  0.6258,
       

In [31]:
import torch.nn as nn 
from torch.nn import functional as F


In [ ]:
class biagram(nn.Module):
    def __init__(self,vacob_size):
        super.__init__()
        self.token_embedding_table = nn.Embedding(vacob_size,vacob_size)

    def forward(self,index,targets):
        logits = self.token_embedding_table(index)
        B,T,C  =  logits.shape
        logits = logits.view(B * T ,C)
        targets  = targets.view(B* T)
        loss = F.cross_entropy(logits,target)

        return logits
    
    def loss(self,logits, targets):
