In [1]:
import torch

c:\Users\riswa\anaconda3\envs\Xray\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(x)
print(y)
print(loss)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
tensor(0.4762, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [3]:
print(w)
print(b)
print(z)

tensor([[-0.2743, -0.5797, -0.6517],
        [-0.5434,  1.6291, -0.6369],
        [ 0.0661,  0.7347,  0.2145],
        [ 0.5526, -0.1895,  0.3291],
        [-0.6134, -0.8996, -0.8434]], requires_grad=True)
tensor([ 1.3267, -1.4681, -1.0972], requires_grad=True)
tensor([ 0.5144, -0.7731, -2.6857], grad_fn=<AddBackward0>)


In [4]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000022456D53D00>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000022456D53F40>


In [9]:
# lossforward()
print(w.grad),
print(b.grad)

tensor([[0.2086, 0.1053, 0.0213],
        [0.2086, 0.1053, 0.0213],
        [0.2086, 0.1053, 0.0213],
        [0.2086, 0.1053, 0.0213],
        [0.2086, 0.1053, 0.0213]])
tensor([0.2086, 0.1053, 0.0213])


In [14]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)+x_data

In [15]:
print(x_data)

tensor([[2, 4],
        [6, 8]])


In [16]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [20]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.IntTensor) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



TypeError: rand_like(): argument 'dtype' must be torch.dtype, not torch.tensortype

In [24]:
print(torch.rand(2,3,dtype=torch.complex64))

tensor([[0.7156+0.1103j, 0.8445+0.5720j, 0.1515+0.6286j],
        [0.4218+0.3622j, 0.8382+0.2845j, 0.9960+0.0393j]])


In [26]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [33]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
# tensor[:,1] = 0
print(tensor)

First row: tensor([0.3063, 0.7210, 0.7882, 0.1915])
First column: tensor([0.3063, 0.5915, 0.5627, 0.2225])
Last column: tensor([0.1915, 0.1591, 0.8019, 0.8767])
tensor([[0.3063, 0.7210, 0.7882, 0.1915],
        [0.5915, 0.7244, 0.8732, 0.1591],
        [0.5627, 0.3979, 0.1649, 0.8019],
        [0.2225, 0.3606, 0.7722, 0.8767]])


In [32]:
import torch

# Create an initial tensor
initial_tensor = torch.zeros((4, 4))  # This can be any tensor
# Create a random tensor with the same shape as the initial tensor
tensor = torch.rand_like(initial_tensor)
print(tensor)



tensor([[0.5377, 0.6016, 0.3060, 0.4421],
        [0.8913, 0.6372, 0.7619, 0.8605],
        [0.7718, 0.1984, 0.9668, 0.0199],
        [0.6208, 0.7006, 0.0072, 0.4514]])


In [34]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])
x[0][1] = 8
print(x)

tensor(6)
tensor([[1, 8, 3],
        [4, 5, 6]])


In [44]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()

print(x.grad)
print(out)
# print(x.)

tensor([[ 2., -2.],
        [ 2.,  2.]])
tensor(4., grad_fn=<SumBackward0>)


In [46]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [47]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)
print(model.parameters())

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
<generator object Module.parameters at 0x00000224589F04A0>


In [48]:
import torch 
import numpy as np


In [50]:
tensor1 = torch.tensor(1)
tensor1.dtype

torch.int64

In [53]:
tensor3d = torch.tensor([[[2,3],[345,24]],
                   [[34,3],[53,32]]])
tensor3d

tensor([[[  2,   3],
         [345,  24]],

        [[ 34,   3],
         [ 53,  32]]])

In [54]:
nparray = np.array([[[  2,   3],
         [345,  24]],
        [[ 34,   3],
         [ 53,  32]]])
nparray

array([[[  2,   3],
        [345,  24]],

       [[ 34,   3],
        [ 53,  32]]])

In [61]:
import torch
import torch.nn.functional as F

# Define tensors
y = torch.tensor([3.0])
x1 = torch.tensor([1.23])
w1 = torch.tensor([1.02])
b1 = torch.tensor([0.5**2])  # Use ** for exponentiation

# Calculate z
z = w1 * x1 + b1

# Apply sigmoid and log sigmoid
a = torch.sigmoid(z)
c = torch.log(torch.sigmoid(z)).item()

# Calculate binary cross-entropy losses
loss1 = F.binary_cross_entropy(a, y.float())
# loss2 = F.binary_cross_entropy(c, y.float())

# Print outputs
print(f"Output of Sigmoid (a): {a.item()}")
# print(f"Output of LogSigmoid (c): {c.item()}")
print(f"Binary Cross Entropy Loss (loss1): {loss1.item()}")
# print(f"Binary Cross Entropy Loss with LogSigmoid (loss2): {loss2.item()}")



Output of Sigmoid (a): 0.8182595372200012
Binary Cross Entropy Loss (loss1): -2.808624267578125


In [63]:
from torch.autograd import grad

w1 = torch.tensor([2.2],requires_grad=True)
b1 = torch.tensor([0.3],requires_grad=True)

z = x1* w1 + b1

a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a,y)

grad_L_w1 = grad(loss,w1,retain_graph= True)

grad_L_b = grad(loss,b1,retain_graph=True)

print(grad_L_b)
print(grad_L_w1)

(tensor([-2.0472]),)
(tensor([-2.5180]),)


In [75]:
loss = F.binary_cross_entropy_with_logits(a,y)


In [76]:
loss.backward()
print()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [73]:
loss

tensor(-1.5795, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [74]:
print(w1.grad)
print(b1.grad)

tensor([-2.5180])
tensor([-2.0472])


In [77]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self,num_inputs,num_outputs):
        super().__init__()
        self.layers = torch.nn.Sequential(
                
            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits
    

In [118]:
mode= NeuralNetwork(50,3)
model.parameters()

<generator object Module.parameters at 0x00000224598EF9E0>

In [80]:
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [79]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 669706


In [85]:
dummy_input = torch.randn(10, 5)  # 10 samples, 5 features each
print(dummy_input)

tensor([[-0.3352, -0.8539,  0.5601,  0.9026,  0.6459],
        [-1.1273,  1.0918,  0.3002,  1.7391, -0.1996],
        [ 0.1206,  0.5931,  0.5245,  0.6859, -0.2437],
        [-1.0841,  0.0396,  1.0108, -0.9748,  0.5006],
        [ 0.4557,  0.3579,  0.5112,  0.0499,  0.5329],
        [-1.5702,  1.0423,  2.6129,  1.9475,  1.7234],
        [ 1.1234,  0.3795,  1.5467,  1.6189,  0.4668],
        [ 1.9525,  0.4730,  0.8637, -1.2427, -0.2587],
        [ 1.2140, -0.8348,  2.2559, -0.1978,  2.5371],
        [ 0.1523, -1.5191, -0.7650,  0.8893,  1.8698]])


In [119]:
import torch

# Example with 5 input features and 3 output classes
model = NeuralNetwork(num_inputs=5, num_outputs=3)

# Create a dummy input (e.g., a batch of 10 samples, each with 5 features)
dummy_input = torch.randn(10, 5)  # 10 samples, 5 features each

# Forward pass through the network
output = model(dummy_input)


In [89]:
from torchsummary import summary
summary(model,(10,5))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1               [-1, 10, 30]             180
              ReLU-2               [-1, 10, 30]               0
            Linear-3               [-1, 10, 20]             620
              ReLU-4               [-1, 10, 20]               0
            Linear-5                [-1, 10, 3]              63
Total params: 863
Trainable params: 863
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.01
----------------------------------------------------------------


In [90]:
output

tensor([[-0.1762, -0.0109,  0.0217],
        [-0.2312, -0.1113,  0.0044],
        [-0.2042, -0.2080, -0.0153],
        [-0.2448,  0.0192, -0.0067],
        [-0.1797,  0.0888,  0.0337],
        [-0.2200, -0.1497,  0.0026],
        [-0.3009, -0.1197,  0.1354],
        [-0.1882, -0.0486,  0.0806],
        [-0.1689, -0.0935,  0.0739],
        [-0.2664, -0.0950,  0.0447]], grad_fn=<AddmmBackward0>)

In [108]:
model.layers

Sequential(
  (0): Linear(in_features=50, out_features=30, bias=True)
  (1): ReLU()
  (2): Linear(in_features=30, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=3, bias=True)
)

In [111]:
model.layers[0].weight.shape

torch.Size([30, 50])

In [121]:
X = torch.rand((1, 50))
X

tensor([[0.0625, 0.1974, 0.9592, 0.4328, 0.1468, 0.5119, 0.3738, 0.5528, 0.6922,
         0.0746, 0.2410, 0.4799, 0.9570, 0.1126, 0.2310, 0.7762, 0.9667, 0.5504,
         0.5084, 0.7241, 0.4021, 0.7969, 0.9967, 0.8578, 0.0082, 0.8865, 0.9722,
         0.7087, 0.3347, 0.4330, 0.1699, 0.4188, 0.8208, 0.3607, 0.4186, 0.4089,
         0.4954, 0.5667, 0.4207, 0.0030, 0.3307, 0.2380, 0.3136, 0.2495, 0.1474,
         0.0951, 0.3214, 0.5720, 0.9921, 0.5445]])

In [123]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x50 and 5x30)

In [117]:
with torch.no_grad:
    out  = model(X)

print(out)

AttributeError: __enter__

In [124]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [126]:
from torch.utils.data import DataChunk,Dataset

class ToyDataset(Dataset):
    def __init__(self,x,y):
        super().__init__()
        self.features = X
        self.labels = y
    def __len__(self):
        return self.labels.shape[0]
    
    def __getitem__(self,index):
        one_x = self.features[index]
        one_y =self.labels[index]

        return one_x,one_y
    

train_ds = ToyDataset(X_train,y_train)
test_ds = ToyDataset(X_test,y_test)


In [127]:
len(train_ds),len(test_ds)

(5, 2)

In [141]:
# from torch.utils.data import *

torch.manual_seed(132)

traine_loader = DataLoader(dataset= train_ds,batch_size = 2,shuffle = True,
                           num_workers=0)
test_loader = DataLoader(dataset=test_ds,batch_size=2,shuffle =False)

In [142]:
print(len(train_ds))  # This should print the number of samples in your dataset
print(X_train.shape)  # Should print the shape of your features
print(y_train.shape)  # Should print the shape of your labels


5
torch.Size([5, 2])
torch.Size([5])


In [143]:
if len(train_ds) > 0:
    for batch in traine_loader:
        features, labels = batch
        print(features.shape, labels.shape)
else:
    print("Dataset is empty.")


IndexError: index 2 is out of bounds for dimension 0 with size 1

In [144]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

IndexError: index 4 is out of bounds for dimension 0 with size 1

In [150]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])
from torch.utils.data import Dataset


class ToyDataset(Dataset):
    def __init__(self, X, y):
        super().__init__()
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]        
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)
test_ds = ToyDataset(X_test, y_test)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [154]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)
        
        loss = F.cross_entropy(logits, labels) # Loss function
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation

Epoch: 001/003 | Batch 000/003 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/003 | Train/Val Loss: 0.65
Epoch: 001/003 | Batch 002/003 | Train/Val Loss: 0.42
Epoch: 002/003 | Batch 000/003 | Train/Val Loss: 0.05
Epoch: 002/003 | Batch 001/003 | Train/Val Loss: 0.13
Epoch: 002/003 | Batch 002/003 | Train/Val Loss: 0.00
Epoch: 003/003 | Batch 000/003 | Train/Val Loss: 0.01
Epoch: 003/003 | Batch 001/003 | Train/Val Loss: 0.00
Epoch: 003/003 | Batch 002/003 | Train/Val Loss: 0.02


In [155]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs)

tensor([[ 2.9320, -4.2563],
        [ 2.6045, -3.8389],
        [ 2.1484, -3.2514],
        [-2.1461,  2.1496],
        [-2.5004,  2.5210]])


In [156]:
print(torch.cuda.is_available())

False


In [158]:
for batch_idx, (features, labels) in enumerate(train_loader):
    print(features,labels)

tensor([[-0.9000,  2.9000],
        [-1.2000,  3.1000]]) tensor([0, 0])
tensor([[ 2.7000, -1.5000],
        [ 2.3000, -1.1000]]) tensor([1, 1])
tensor([[-0.5000,  2.6000]]) tensor([0])
